"""AnvilModel — extends RenderCVModel with an optional `anvil` section.

Why:
    AnvilModel is the root Pydantic model for Anvil YAML files. It inherits
    all rendercv fields (cv, design, locale, settings) and adds the optional
    `anvil` field for Anvil-specific configuration. Any valid rendercv YAML
    is also valid Anvil YAML — the `anvil` section is entirely optional.

Note:
    RenderCVModel inherits from BaseModelWithoutExtraKeys (extra="forbid"),
    so we must explicitly add the `anvil` field. We do NOT change the parent's
    config — unknown fields other than `anvil` are still rejected.
"""

from __future__ import annotations

import pydantic

from anvilcv.schema.anvil_config import AnvilConfig
from anvilcv.schema.variant import VariantMetadata
from anvilcv.vendor.rendercv.schema.models.rendercv_model import RenderCVModel


class AnvilModel(RenderCVModel):
    """Root model for Anvil YAML files.

    Extends RenderCVModel with optional `anvil` section containing provider
    config, GitHub integration, variant tracking, and deployment settings.
    """

    anvil: AnvilConfig | None = pydantic.Field(
        default=None,
        title="Anvil Configuration",
        description=(
            "Anvil-specific configuration: AI providers, GitHub integration, "
            "variant output, and deployment settings. Optional — omitting this "
            "section makes the file behave identically to a rendercv YAML."
        ),
    )

    variant: VariantMetadata | None = pydantic.Field(
        default=None,
        title="Variant Metadata",
        description=(
            "Provenance metadata for tailored variants. Present only in files "
            "generated by `anvil tailor`. Do not edit manually."
        ),
    )
